import { Inter } from "next/font/google";
import "./globals.css";
import { PublicHeader } from "./components/public-header";
import { SessionProvider } from "next-auth/react";
import DbConnect from "@/utils/dbConnect";
import { auth } from "@/auth";
import User from "@/models/User";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
   DbConnect();
   let  session = await auth();
   
    if(session){
      if(session.user){
         let user = await User.findOne({
           name: session.user.name,
           email: session.user.email,
         })
         if(!user){
          user = await User.create({name:session.user.name,email:session.user.email})
         }
      }
    }
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <PublicHeader />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
